# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

row_count=spark.sql("""select * from gcp_mysql_fc_wd36.logistics.shipments1 where updated_at>(SELECT COALESCE(MAX(updated_at), '1970-01-01')  FROM catalog2_we47.schema2_we47.bronze_shipments1)""").count()
print(row_count)

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from catalog2_we47.schema2_we47.bronze_shipments1;

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from catalog2_we47.schema2_we47.silver_shipments_dlt1;

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from catalog2_we47.schema2_we47.gold_shipments_agg;

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from catalog2_we47.schema2_we47.audit_log;
