# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from lakehousecat.deltadb.drugstbl
# MAGIC --where drugname in ('Itrazole','Itraconazole');
# MAGIC where uniqueid in('232128','232129','232130');

# COMMAND ----------

# MAGIC %sql
# MAGIC insert into lakehousecat.deltadb.drugstbl values --(uniqueid,drugname,condition,rating,date,usefulcount),
# MAGIC  (232141,null,'fever',10,'2016-07-02',4),
# MAGIC  (232142,'fail','fever',11,'2016-07-02',4),
# MAGIC  (232143,null,'fever',11,'2016-07-02',4)

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from catalog2_we47.default.drugstbl_medal_bronze3 
# MAGIC --where rating IN (9,10)
# MAGIC --and usefulcount >1
# MAGIC where uniqueid in('232138','232139','232140');
# MAGIC --and drugname in ('Itrazole','Itraconazole','Itazole');
# MAGIC
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from catalog2_we47.default.drugstbl_medal_gold_mv2
# MAGIC where drugname in ('drop',null);
